version: '3.8'

services:
  data-transfer:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - TARGET_DIR=/app/target
      - BINLOG_INCR_SYNC_INTERVAL_SECONDS=5
      
      # DS1 配置
      - DS1_MYSQL_HOST=${DS1_MYSQL_HOST}
      - DS1_MYSQL_PORT=${DS1_MYSQL_PORT:-3306}
      - DS1_MYSQL_USER=${DS1_MYSQL_USER}
      - DS1_MYSQL_PASSWORD=${DS1_MYSQL_PASSWORD}
      - DS1_MYSQL_SERVER_ID=${DS1_MYSQL_SERVER_ID}
      - DS1_TABLES_LIST=${DS1_TABLES_LIST}
      - DS1_ENABLE_FULL_SYNC=${DS1_ENABLE_FULL_SYNC:-false}
      - DS1_ENABLE_INCREMENTAL_SYNC=${DS1_ENABLE_INCREMENTAL_SYNC:-true}
      - DS1_ENABLE_SFTP_UPLOAD=${DS1_ENABLE_SFTP_UPLOAD:-true}
      
      # DS2 配置
      - DS2_MYSQL_HOST=${DS2_MYSQL_HOST}
      - DS2_MYSQL_PORT=${DS2_MYSQL_PORT:-3306}
      - DS2_MYSQL_USER=${DS2_MYSQL_USER}
      - DS2_MYSQL_PASSWORD=${DS2_MYSQL_PASSWORD}
      - DS2_MYSQL_SERVER_ID=${DS2_MYSQL_SERVER_ID}
      - DS2_TABLES_LIST=${DS2_TABLES_LIST}
      - DS2_ENABLE_FULL_SYNC=${DS2_ENABLE_FULL_SYNC:-false}
      - DS2_ENABLE_INCREMENTAL_SYNC=${DS2_ENABLE_INCREMENTAL_SYNC:-true}
      - DS2_ENABLE_SFTP_UPLOAD=${DS2_ENABLE_SFTP_UPLOAD:-true}
      
      # 处理器配置
      - ENABLED_PROCESSORS=${ENABLED_PROCESSORS:-sftp}
      
      # SFTP 输出配置
      - OUTPUT_SFTP_HOST=${OUTPUT_SFTP_HOST}
      - OUTPUT_SFTP_PORT=${OUTPUT_SFTP_PORT:-22}
      - OUTPUT_SFTP_USER=${OUTPUT_SFTP_USER}
      - OUTPUT_SFTP_PASSWORD=${OUTPUT_SFTP_PASSWORD}
      - OUTPUT_SFTP_REMOTE_DIR=${OUTPUT_SFTP_REMOTE_DIR:-/upload}
    volumes:
      - ../target:/app/target