name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Run tests
      run: |
        pytest

    - name: Build Docker image
      run: |
        docker build -t ${{ github.repository }}:${{ github.sha }} -f docker/Dockerfile .

    - name: Login to Docker Hub
      if: github.event_name == 'push'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker image
      if: github.event_name == 'push'
      run: |
        docker tag ${{ github.repository }}:${{ github.sha }} ${{ github.repository }}:latest
        docker push ${{ github.repository }}:${{ github.sha }}
        docker push ${{ github.repository }}:latest